# stages:
#   - build

# build:
#   stage: build
#   image: docker:latest
#   tags: 
#     - macos
#     - dm_project
#   services:
#   - name: 'docker:20.10.12-dind'
#   script:
#     - |
#     - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
#     - docker build --pull -t "$CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:latest" .
#     - docker push "$CI_REGISTRY_IMAGE/$CI_PROJECT_NAME"
variables:
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:latest"

stages:
  - build

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build --pull -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE


