name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # You can change this to the desired branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # Use your runner
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx (for multi-platform builds if needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub (optional if you're pushing the image)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t mydockerhubusername/myapp:latest .
        
      # Push the Docker image (optional)
      - name: Push Docker image
        run: |
          docker push mydockerhubusername/myapp:latest
