name: Build Docker Image Locally

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

     # run the container for testing (remove if not needed)
     # - name: Run Docker container for testing
     #   run: |
     #    docker run --rm myapp:latest python3 orchestrator.py

